import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
const base='http://127.0.0.1:8765';
const health=await fetch(base+'/api/health').then(r=>r.json());
assert.equal(health.product,'AI Evolution 360 Studio');
const headers={'X-Studio-Token':health.token,'Content-Type':'application/json'};
assert.equal((await fetch(base+'/api/upload?name=bad.mp4',{method:'POST',body:'bad'})).status,403);
assert.equal((await fetch(base+'/api/upload?name=bad.exe',{method:'POST',headers,body:'bad'})).status,400);
const corrupt=await fetch(base+'/api/upload?name=qa-invalid.mp4',{method:'POST',headers:{'X-Studio-Token':health.token},body:'This is not a video.'});
assert.equal(corrupt.status,400);const bad=await corrupt.json();assert.equal(bad.project.state,'failed');
await fetch(`${base}/api/projects/${bad.project.id}/archive`,{method:'POST',headers,body:'{}'});
const projects=await fetch(base+'/api/projects').then(r=>r.json());
const ready=projects.find(p=>p.state==='ready');assert.ok(ready,'Need successful integration project');
const sog=await fetch(`${base}/api/projects/${ready.id}/sog`);assert.equal(sog.status,200);const data=Buffer.from(await sog.arrayBuffer());assert.equal(data.subarray(0,2).toString(),'PK');
const range=await fetch(`${base}/api/projects/${ready.id}/sog`,{headers:{Range:'bytes=0-7'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,8);
const ply=await fetch(`${base}/api/projects/${ready.id}/ply`,{headers:{Range:'bytes=0-3'}});assert.equal(Buffer.from(await ply.arrayBuffer()).toString(),'ply\n');
assert.match(ply.headers.get('content-disposition'),/attachment/);
const hostile=await fetch(`${base}/api/projects/${ready.id}/archive`,{method:'POST',headers:{...headers,Origin:'https://unrelated.example'},body:'{}'});assert.equal(hostile.status,403);
const mismatch=await fetch(`${base}/api/projects/${ready.id}/start`,{method:'POST',headers,body:JSON.stringify({preset:'fast',mode:'equirect'})});assert.equal(mismatch.status,400);
const report={date:new Date().toISOString(),passed:['health','token gate','extension validation','corrupt video failure','archive','SOG signature','range requests','PLY download','origin guard','camera projection validation'],project:ready.id,sogBytes:data.length};
writeFileSync('docs/verification/studio-api-tests.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
