const $ = id => document.getElementById(id);
const stages=['Odczyt filmu','Wybór ostrych klatek','Przygotowanie danych','Odtworzenie kamer','Trening sceny 3D','Optymalizacja SOG','Przygotowanie podglądu','Gotowe'];
const videoStages=stages;
const stateNames={panorama:'Panorama gotowa',uploaded:'Materiał dodany',uploading:'Dodawanie filmu',processing:'Przetwarzanie',cancelling:'Anulowanie',ready:'Scena gotowa',failed:'Wymaga uwagi',cancelled:'Anulowano',interrupted:'Przerwano'};
let sourceKind='video',panorama=null,photoIndex=0,photoGalleryKey='';
let routeIndex=0,routeCount=0,routeReverse=false;
let token='',health={},projects=[],selected=null,preset='max',viewer=null,viewerKey='',viewerGeneration=0,upload=null,page='studio',polling=false,configuring=false,librarySignature='';
const minimumPhotos=()=>3;
const photoCount=n=>`${n} ${n===1?'zdjęcie':n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?'zdjęcia':'zdjęć'} 360°`;
const bytes=n=>!n?'—':n>=1024**3?(n/1024**3).toFixed(2)+' GB':(n/1024**2).toFixed(1)+' MB';
const duration=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const visible=(id,show)=>$(id).hidden=!show;
function toast(message){$('toast').textContent=message;visible('toast',true);clearTimeout(toast.timer);toast.timer=setTimeout(()=>visible('toast',false),6500);}
async function api(path,body){const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Studio-Token':token},body:body===undefined?undefined:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Nie udało się wykonać operacji.');return data;}
function showPage(name){page=name;for(const id of ['studio','library','guide'])visible(id,id===name);document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(viewer)viewer.state.inputEnabled=name==='studio';if(name==='library')renderLibrary();window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));
function disableTools(disabled){for(const id of ['orbit','fly','frame','reset','fullscreen'])$(id).disabled=disabled;}
function clearViewer(){try{panorama?.destroy();}catch{}panorama=null;visible('route-controls',false);viewerGeneration++;const previous=viewer;viewer=null;viewerKey='';try{previous?.destroy();}catch(error){console.warn('Zamykanie podglądu GPU:',error);}$('viewer').replaceChildren();disableTools(true);visible('viewer-loading',false);visible('quality-row',false);$('fps').textContent='';}
function reset(){if(upload)return;selected=null;sourceKind='video';for(const k of ['video','photos']){$('source-'+k).classList.toggle('selected',k==='video');$('source-'+k).setAttribute('aria-pressed',String(k==='video'));}$('dropzone').querySelector('strong').textContent='Przeciągnij film tutaj';$('dropzone').querySelector('small').textContent='INSTA360 · INSV, MP4, MOV · DO 20 GB';$('source-panel').querySelector('.tip p').textContent='Najlepszy start? Spokojny spacer 20–60 sekund. Poruszaj kamerą między pozycjami i utrzymuj ostrość.';visible('cleanup-panel',false);visible('blender-panel',false);preset='max';choosePreset(preset);$('photos').value='';$('controls-hint').textContent='PRZECIĄGNIJ, ABY OBRACAĆ · KÓŁKO, ABY PRZYBLIŻAĆ';photoGalleryKey='';visible('photo-gallery',false);visible('source-tabs',true);configuring=false;poll.restored=true;selected=null;localStorage.removeItem('studio-project');clearViewer();visible('source-info',false);visible('dropzone',true);visible('upload-state',false);visible('preview-empty',true);visible('source-preview',false);visible('processing-panel',false);visible('setup-panel',true);visible('result-panel',false);visible('error-box',false);visible('logs',false);visible('export-bar',false);visible('new-project',false);$('preview-title').textContent='Ta przestrzeń może być Twoja';$('preview-badge').textContent='PODGLĄD';$('file').value='';setStart();showPage('studio');}
$('new-project').onclick=reset;$('library-new').onclick=reset;
function choosePreset(name){preset=name;document.querySelectorAll('[data-preset]').forEach(b=>{const active=b.dataset.preset===name;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});const p=health.presets?.[preset];if(p)$('preset-note').textContent=`${(selected?.kind==='photos'||!selected&&sourceKind==='photos')?'Wszystkie zdjęcia':`Do ${p.frames} klatek na tor`} · ${(selected?.kind==='photos'&&selected.mode!=='fisheye'||!selected&&sourceKind==='photos')?Math.min(3840,p.size*2):p.size} px · ${p.iterations.toLocaleString('pl-PL')} kroków treningu.`;}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>choosePreset(b.dataset.preset));
function setStart(){const busy=selected&&['processing','cancelling','uploading'].includes(selected.state);const other=health.busy&&health.busy!==selected?.id;$('start').disabled=!health.ready||!selected?.metadata||busy||Boolean(other)||Boolean(upload)||(['processing','cancelling'].includes(selected?.cleanup?.status)||['processing','cancelling'].includes(selected?.meshExport?.status))||(selected?.kind==='photos'&&(!selected.uploadComplete||selected.photos.length<minimumPhotos(selected)));$('start').firstElementChild.textContent=selected?.kind==='photos'?'Połącz zdjęcia w przestrzeń 3D':'Utwórz przestrzeń 3D';$('start-note').textContent=other?'Inny projekt jest teraz przetwarzany. Otworzysz go w bibliotece.':!health.ready?'Czekamy na gotowość lokalnego silnika.':!selected?.metadata?'Dodaj film lub zdjęcia 360°. Przetwarzanie działa lokalnie.':selected?.kind==='photos'&&selected.photos.length<minimumPhotos(selected)?'Panorama jest gotowa do oglądania. Rekonstrukcja 3D wymaga minimum 3 zdjęć, najlepiej 12–30 zdjęć z różnych pozycji.':'Praca na GPU może potrwać kilka–kilkadziesiąt minut. Zostaw aplikację uruchomioną.';}
function renderProject(project, fresh=false){
    const stages=project.kind==='photos'?['Odczyt zdjęć','Przygotowanie panoram','Przygotowanie danych','Łączenie pozycji kamer','Trening sceny 3D','Optymalizacja SOG','Przygotowanie podglądu','Gotowe']:videoStages;const changed=selected?.id!==project.id;selected=project;localStorage.setItem('studio-project',project.id);
    visible('source-tabs',false);visible('dropzone',false);visible('upload-state',false);visible('source-info',true);visible('new-project',true);
    $('filename').textContent=project.kind==='photos'?photoCount(project.photos.length):project.sourceName||project.name;$('file-extra').textContent=`${bytes(project.metadata?.bytes)} · ${new Date(project.createdAt).toLocaleDateString('pl-PL')}`;
    const m=project.metadata;$('metadata').innerHTML=m?`<div><span>ROZDZIELCZOŚĆ</span><strong>${m.width} × ${m.height}</strong></div><div><span>CZAS</span><strong>${duration(m.duration)}</strong></div><div><span>KLATKI / S</span><strong>${Math.round(m.fps*100)/100}</strong></div>`:'<p class="muted">Brak poprawnych danych filmu. Dodaj inny plik.</p>';
    if(changed||fresh){if(project.cleanup?.strength)$('cleanup-strength').value=project.cleanup.strength;$('camera-mode').value=project.mode||m?.suggestedMode||'auto';choosePreset(project.preset||preset);}
    if(project.kind==='photos'&&m)$('metadata').innerHTML=`<div><span>ZDJĘCIA</span><strong>${project.photos.length}</strong></div><div><span>FORMAT</span><strong>${project.mode==='fisheye'?'INSP · 2 obiektywy':'360° · 2:1'}</strong></div><div><span>ROZDZIELCZOŚĆ</span><strong>${m.width} × ${m.height}</strong></div>`;
    modeNote();
    const busy=['processing','cancelling'].includes(project.state),ready=project.state==='ready';$('source-preview').classList.toggle('is-processing',busy);$('source-panel').querySelector('.tip p').innerHTML=project.kind==='photos'?'Najlepszy start? <strong>12–30 panoram z różnych pozycji.</strong><br>Jedno zdjęcie: rozglądanie się bez odtworzonej głębi.':'Najlepszy start? <strong>Spokojny spacer 20–60 sekund.</strong><br>Instrukcję znajdziesz w zakładce „Jak przygotować materiał”.';
    if(changed||fresh)configuring=false;
    visible('setup-panel',!busy&&(!ready||configuring)&&!(project.kind==='photos'&&project.photos.length<minimumPhotos(project)));visible('processing-panel',busy);visible('result-panel',ready&&!configuring);visible('logs',project.attempt>0);visible('error-box',Boolean(project.error));
    $('camera-mode').disabled=busy||project.kind==='photos';document.querySelectorAll('[data-preset]').forEach(b=>b.disabled=busy);
    if(project.error){$('error-title').textContent=project.state==='cancelled'?'Przetwarzanie anulowane':project.state==='interrupted'?'Praca została przerwana':'Projekt wymaga uwagi';$('error-message').textContent=project.error;}
    if(busy){$('processing-title').textContent=project.state==='cancelling'?'Zatrzymujemy zadanie…':'Odtwarzamy przestrzeń';$('current-stage').textContent=stages[project.stage];$('native-percent').textContent=project.progress===null?'':project.progress+'%';if(project.progress===null)$('native-progress').removeAttribute('value');else $('native-progress').value=project.progress;$('cancel-job').disabled=project.state==='cancelling';$('stages').innerHTML=stages.map((s,i)=>`<li class="${i<project.stage?'done':i===project.stage?'current':''}"><span>${i<project.stage?'✓':String(i+1).padStart(2,'0')}</span>${s}</li>`).join('');}
    if(ready){$('result-summary').textContent=`${project.registeredCameras||'—'} pozycji kamer · ${bytes(project.output.bytes)} SOG`;$('output-size').textContent=`${bytes(project.output.bytes)} · otwarty format Gaussian Splat`;$('download-sog').href=`/api/projects/${project.id}/sog?download=1`;$('download-ply').href=`/api/projects/${project.id}/ply`;visible('export-bar',true);const key=project.id+':'+project.attempt+':'+project.output.web;if(!viewerKey.startsWith('panorama:'+project.id)&&viewerKey!==key)loadViewer(key,`/api/projects/${project.id}/sog?v=${encodeURIComponent(project.output.web)}`,`/api/projects/${project.id}/settings?v=${encodeURIComponent(project.output.web)}`,project.name,false);}
    else if(project.kind==='photos'&&!busy&&project.uploadComplete){visible('export-bar',false);const key='panorama:'+project.id+':'+photoIndex;if(viewerKey!==key)loadPanorama(project,changed?0:photoIndex);}
    else {visible('export-bar',false);if(changed||fresh||viewerKey){clearViewer();visible('preview-empty',false);visible('source-preview',true);$('source-poster').src=`/api/projects/${project.id}/poster`;}$('preview-title').textContent=project.name;$('preview-badge').textContent=busy?'PRZETWARZANIE':'FILM ŹRÓDŁOWY';$('source-preview-title').textContent=busy?'Z klatek powstaje przestrzeń.':'Zaraz nabierze głębi.';}
    renderPhotoGallery(project,busy);renderCleanup(project);renderBlender(project);
    $('download-log').href=`/api/projects/${project.id}/logfile`;setStart();updateElapsed();
}
function modeNote(){if(selected?.kind==='photos'&&selected.mode==='fisheye'){$('mode-note').textContent='INSP: oba obiektywy są rozdzielane do rekonstrukcji, bez stratnego zszywania. Do 3D dodaj minimum 3 zdjęcia, najlepiej 12–30.';return;}const mode=$('camera-mode').value;const text={fisheye:'Dwie soczewki w jednym INSV. Telemetrię oceni silnik podczas rekonstrukcji.',equirect:'Pełna panorama 360° w proporcji 2:1, bez reframingu i cięć.',perspective:'Zwykła kamera. Dla eksportu 360° 2:1 wybierz „Panorama 360°”.',auto:'INSV: dwie soczewki. MP4/MOV: tryb 360° tylko przy wykrytym oznaczeniu panoramy.'};$('mode-note').textContent=text[mode];}
$('camera-mode').replaceChildren(...[['auto','Wykryj automatycznie'],['fisheye','Insta360 — dwie soczewki'],['equirect','Panorama 360° — obraz 2:1'],['perspective','Zwykłe wideo — kamera perspektywiczna']].map(([value,label])=>new Option(label,value)));
$('camera-mode').onchange=modeNote;
async function uploadFile(file){
    if(!file||upload)return;
    if(!/\.(insv|mp4|mov)$/i.test(file.name))return toast('Wybierz film INSV, MP4 lub MOV.');
    if(file.size>20*1024**3||file.size===0)return toast('Wybierz niepusty plik do 20 GB.');
    if(!token)return toast('Poczekaj na połączenie z lokalnym serwerem.');
    reset();visible('dropzone',false);visible('upload-state',true);$('upload-name').textContent=file.name;$('upload-progress').value=0;$('upload-label').textContent='Dodawanie filmu · 0%';
    const xhr=new XMLHttpRequest();upload=xhr;setStart();xhr.open('POST','/api/upload?name='+encodeURIComponent(file.name));xhr.setRequestHeader('X-Studio-Token',token);xhr.setRequestHeader('Content-Type','application/octet-stream');
    xhr.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(100*e.loaded/e.total);$('upload-progress').value=p;$('upload-label').textContent=p===100?'Odczyt parametrów filmu…':`Dodawanie filmu · ${p}%`;}};
    xhr.onload=()=>{upload=null;try{const data=JSON.parse(xhr.responseText);if(xhr.status>=400){if(data.project)renderProject(data.project,true);else reset();toast(data.error);}else{renderProject(data,true);toast('Film dodany. Wybierz jakość i utwórz przestrzeń.');}poll();}catch{reset();toast('Serwer zwrócił nieprawidłową odpowiedź. Sprawdź, czy aplikacja działa.');}setStart();};
    xhr.onerror=()=>{upload=null;reset();toast('Utracono połączenie podczas dodawania filmu. Spróbuj ponownie.');};xhr.onabort=()=>{upload=null;reset();toast('Dodawanie filmu anulowane.');};xhr.send(file);
}
$('dropzone').onclick=()=>$(sourceKind==='photos'?'photos':'file').click();$('file').onchange=e=>uploadFile(e.target.files[0]);$('photos').onchange=e=>uploadPhotos([...e.target.files]);$('cancel-upload').onclick=()=>upload?.abort();
for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('drag');});
for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('drag');if(event==='drop'){if(sourceKind==='photos')uploadPhotos([...e.dataTransfer.files]);else uploadFile(e.dataTransfer.files[0]);}});
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>e.preventDefault());
$('start').onclick=async()=>{if(!selected)return;$('start').disabled=true;try{const p=await api(`/api/projects/${selected.id}/start`,{preset,mode:$('camera-mode').value});health.busy=p.id;renderProject(p,true);}catch(e){toast(e.message);setStart();}};
$('cancel-job').onclick=async()=>{if(!selected)return;$('cancel-job').disabled=true;try{await api(`/api/projects/${selected.id}/cancel`,{});await poll();}catch(e){toast(e.message);$('cancel-job').disabled=false;}};
$('reprocess').onclick=()=>{choosePreset('max');configuring=true;visible('result-panel',false);visible('setup-panel',true);$('setup-panel').scrollIntoView({behavior:'smooth',block:'center'});};
async function loadViewer(key,contentUrl,settingsUrl,name,demo){
    clearViewer();viewerKey=key;const generation=viewerGeneration;visible('preview-empty',false);visible('source-preview',false);visible('viewer-loading',true);$('viewer-percent').textContent='';$('preview-title').textContent=name;$('preview-badge').textContent=demo?'TEST SYNTETYCZNY':'INTERAKTYWNE 3D';
    try{
        const {createViewer}=await import('/viewer/index.js');if(generation!==viewerGeneration)return;
        const settings=await fetch(settingsUrl).then(r=>{if(!r.ok)throw new Error('Brak ustawień sceny.');return r.json();});
        const handle=await createViewer({container:$('viewer'),contentUrl,contentFilename:'scene.sog',settings,ui:false,noanim:true,lang:'en'});
        if(generation!==viewerGeneration){handle.destroy();return;}viewer=handle;
        routeCount=Math.floor((settings.annotations?.length||0)/2);routeIndex=routeCount>1?1:0;routeReverse=false;
        const ready=()=>{if(generation!==viewerGeneration)return;clearTimeout(loadTimer);visible('viewer-loading',false);disableTools(false);visible('quality-row',true);handle.resetCamera();handle.state.cameraMode=settings.cameras?.length?'fly':'orbit';handle.state.animationPaused=true;handle.state.performanceMode=false;handle.state.inputEnabled=page==='studio';$('performance').checked=handle.state.performanceMode;cameraButtons(handle.state.cameraMode);visible('route-controls',routeCount>0);$('route-label').textContent=`Punkt ${routeIndex+1} / ${routeCount}`;};
        const loadTimer=setTimeout(()=>{if(generation===viewerGeneration&&!handle.state.loaded){visible('viewer-loading',false);toast('Scena nie została jeszcze wyrenderowana. Sprawdź akcelerację sprzętową przeglądarki lub otwórz projekt ponownie.');}},90000);
        handle.app.assets.on('error',error=>{if(generation===viewerGeneration){clearTimeout(loadTimer);visible('viewer-loading',false);toast('Błąd ładowania sceny: '+String(error));}});
        handle.events.on('progress:changed',p=>{if(generation===viewerGeneration)$('viewer-percent').textContent=Math.round(p)+'%';});
        handle.events.on('cameraMode:changed',cameraButtons);
        if(handle.state.loaded)ready();else handle.events.once('loaded:changed',ready);
    }catch(e){if(generation===viewerGeneration){visible('viewer-loading',false);visible('preview-empty',true);toast('Nie udało się otworzyć podglądu: '+e.message);}}
}
function cameraButtons(mode){$('orbit').classList.toggle('active',mode==='orbit');$('fly').classList.toggle('active',mode==='fly');$('controls-hint').textContent=mode==='fly'?'PRZYTRZYMAJ PRAWY PRZYCISK + WASD · Q / E W GÓRĘ I W DÓŁ':'PRZECIĄGNIJ, ABY OBRACAĆ · KÓŁKO, ABY PRZYBLIŻAĆ';}
$('orbit').onclick=()=>{if(viewer?.state.loaded)viewer.state.cameraMode='orbit';};$('fly').onclick=()=>{if(viewer?.state.loaded){viewer.state.cameraMode='fly';viewer.state.gamingControls=false;toast('Swobodny lot: przytrzymaj prawy przycisk myszy i użyj WASD.');}};
$('frame').onclick=()=>viewer?.frameScene();$('reset').onclick=()=>{if(!viewer?.state.loaded)return;viewer.resetCamera();routeIndex=routeCount>1?1:0;routeReverse=false;if(routeCount){viewer.state.cameraMode='fly';$('route-label').textContent=`Punkt ${routeIndex+1} / ${routeCount}`;}};$('fullscreen').onclick=()=>{$('preview-area').requestFullscreen().catch(e=>toast(e.message));};$('performance').onchange=()=>{if(viewer)viewer.state.performanceMode=$('performance').checked;};
document.addEventListener('focusin',e=>{if(viewer)viewer.state.inputEnabled=page==='studio'&&!e.target.matches('input,select,textarea');});
$('demo').onclick=()=>loadViewer('demo','/demo/scene.sog','/demo/settings.json','Przykład sterowania · scena syntetyczna',true);
$('source-poster').onerror=()=>{$('source-poster').style.opacity='0';};$('source-poster').onload=()=>{$('source-poster').style.opacity='.55';};
function renderLibrary(){const list=projects.filter(p=>Boolean(p.archived)===$('show-archived').checked);const signature=JSON.stringify([$('show-archived').checked,list.map(p=>[p.id,p.state,p.attempt,p.name,p.output?.bytes])]);if(signature===librarySignature)return;librarySignature=signature;$('library-summary').textContent=`${list.length} ${list.length===1?'projekt':'projektów'} · przechowywane lokalnie`;$('projects').innerHTML=list.length?list.map(p=>`<article class="project-card"><div class="project-image"><img src="/api/projects/${p.id}/poster" alt="Klatka z projektu" loading="lazy"><span class="badge">${escape(stateNames[p.state]||p.state)}</span></div><div class="project-body"><h2>${escape(p.name)}</h2><p>${new Date(p.createdAt).toLocaleDateString('pl-PL')} · ${p.kind==='photos'?photoCount(p.photos.length):p.metadata?duration(p.metadata.duration):'Brak metadanych'} · ${p.output?bytes(p.output.bytes)+' SOG':bytes(p.metadata?.bytes)}</p><div class="project-actions"><button class="secondary" data-open="${p.id}">${p.state==='ready'?'Otwórz przestrzeń':'Otwórz projekt'} ↗</button><button class="text-button" data-archive="${p.id}">${p.archived?'Przywróć':'Archiwizuj'}</button></div></div></article>`).join(''):`<div class="empty-library"><h2>${$('show-archived').checked?'Archiwum jest puste.':'Tu zaczną się Twoje przestrzenie.'}</h2><p>Dodaj pierwszy film i wróć do niego w dowolnej chwili.</p><button class="secondary" id="empty-new">+ Dodaj film</button></div>`;
    $('projects').querySelectorAll('img').forEach(img=>img.onerror=()=>img.style.visibility='hidden');
    $('projects').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{renderProject(projects.find(p=>p.id===b.dataset.open),true);showPage('studio');});
    $('projects').querySelectorAll('[data-archive]').forEach(b=>b.onclick=async()=>{try{await api(`/api/projects/${b.dataset.archive}/archive`,{});await poll();renderLibrary();}catch(e){toast(e.message);}});
    if($('empty-new'))$('empty-new').onclick=reset;
}
$('show-archived').onchange=renderLibrary;
async function loadLogs(){if(selected?.attempt&&$('logs').open){try{$('log-text').textContent=(await api(`/api/projects/${selected.id}/logs`)).text;$('log-text').scrollTop=$('log-text').scrollHeight;}catch(e){$('log-text').textContent=e.message;}}}
$('logs').ontoggle=loadLogs;
function updateElapsed(){if(selected?.startedAt){const end=selected.finishedAt?Date.parse(selected.finishedAt):Date.now();$('elapsed').textContent=duration(Math.max(0,(end-Date.parse(selected.startedAt))/1000));}}
async function poll(){if(polling)return;polling=true;try{const [h,list]=await Promise.all([api('/api/health'),api('/api/projects')]);health=h;token=h.token;projects=list;$('project-count').textContent=projects.filter(p=>!p.archived).length;$('engine-label').textContent=h.ready?'Silnik gotowy do pracy':h.engine;$('gpu-label').textContent=h.ready?h.gpu.replace(/^\d+\s+/, '').replace(/\s+uuid:.*/, '').replace('discrete', '·'):h.engine;$('engine-dot').style.background=h.ready?'#acdabb':'#dda894';choosePreset(preset);if(selected){const p=list.find(p=>p.id===selected.id);if(p)renderProject(p);}else if(!upload&&!poll.restored){poll.restored=true;const saved=localStorage.getItem('studio-project');const p=list.find(p=>p.id===saved&&!p.archived);if(p)renderProject(p,true);}if(page==='library')renderLibrary();setStart();await loadLogs();}catch{$('engine-label').textContent='Brak połączenia z aplikacją';$('gpu-label').textContent='Uruchom START-STUDIO.cmd. Ponowimy połączenie automatycznie.';health.ready=false;setStart();}finally{polling=false;}}
setInterval(poll,1800);setInterval(()=>{updateElapsed();if(viewer?.state.loaded){const fps=viewer.app.stats?.frame?.fps;$('fps').textContent=Number.isFinite(fps)&&fps>0?Math.round(fps)+' FPS':'';}},1000);poll();

api('/api/demo').then(({available})=>{visible('demo',available);const note=$('demo').nextElementSibling;if(note)note.hidden=!available;}).catch(()=>visible('demo',false));

function routeMove(delta,turn=false){if(!viewer?.state.loaded||!routeCount)return;routeIndex=(routeIndex+delta+routeCount)%routeCount;routeReverse=turn?!routeReverse:false;viewer.selectAnnotation(routeIndex*2+(routeReverse?1:0));$('route-label').textContent=`Punkt ${routeIndex+1} / ${routeCount}`;}
$('route-prev').onclick=()=>routeMove(-1);$('route-next').onclick=()=>routeMove(1);$('route-turn').onclick=()=>routeMove(0,true);
function selectSource(kind){if(upload)return;reset();sourceKind=kind;choosePreset(preset);$('source-panel').querySelector('.tip p').textContent=kind==='photos'?'Zalecamy 12–30 panoram z różnych pozycji. Instrukcję znajdziesz w zakładce „Jak przygotować materiał”.':'Zacznij od spokojnego spaceru 20–60 sekund. Instrukcję znajdziesz w zakładce „Jak przygotować materiał”.';for(const k of ['video','photos']){$('source-'+k).classList.toggle('selected',k===kind);$('source-'+k).setAttribute('aria-pressed',String(k===kind));}$('dropzone').querySelector('strong').textContent=kind==='photos'?'Dodaj jedno lub kilka zdjęć 360°':'Przeciągnij film tutaj';$('dropzone').querySelector('small').textContent=kind==='photos'?'INSTA360 INSP LUB PANORAMY JPG / PNG · DO 100 ZDJĘĆ':'INSTA360 · INSV, MP4, MOV · DO 20 GB';}
$('source-video').onclick=()=>selectSource('video');$('source-photos').onclick=()=>selectSource('photos');
function renderPhotoGallery(project,busy){const photos=project.kind==='photos'&&project.uploadComplete;visible('photo-gallery',photos);if(!photos)return;$('photo-gallery').querySelector('p').textContent=project.mode==='fisheye'?'Podgląd INSP jest przybliżonym zszyciem: szew i horyzont mogą być niedokładne. Rekonstrukcja 3D korzysta z oryginalnych obiektywów, a nie tego podglądu.':'Panorama pozwala się rozglądać z jednego punktu. Dopiero rekonstrukcja wielu zdjęć odtwarza głębię.';const key=project.id+':'+project.photos.length;if(photoGalleryKey!==key){photoGalleryKey=key;photoIndex=0;$('photo-select').replaceChildren(...project.photos.map((p,i)=>new Option(`${i+1}. ${p.name}`,String(i))));}$('photo-select').disabled=busy;$('show-panorama').disabled=busy;visible('show-scene',project.state==='ready'&&Boolean(panorama));}
function loadPanorama(project,index=0){clearViewer();photoIndex=index;viewerKey='panorama:'+project.id+':'+index;visible('preview-empty',false);visible('source-preview',false);visible('viewer-loading',false);$('preview-title').textContent=project.photos[index].name;$('preview-badge').textContent=project.mode==='fisheye'?'INSP · PRZYBLIŻONY PODGLĄD':'PANORAMA 360° · BEZ GŁĘBI';$('controls-hint').textContent='PRZECIĄGNIJ, ABY SIĘ ROZEJRZEĆ · KÓŁKO, ABY PRZYBLIŻYĆ';try{panorama=window.pannellum.viewer('viewer',{type:'equirectangular',panorama:`/api/projects/${project.id}/panorama?index=${index}`,autoLoad:true,showControls:true,hfov:90,strings:{loadingLabel:'Wczytywanie panoramy…'}});panorama.on('error',()=>toast('Nie udało się wyświetlić panoramy. Sprawdź obsługę WebGL.'));$('fullscreen').disabled=false;}catch(e){toast('Błąd panoramy: '+e.message);}visible('show-scene',project.state==='ready');}
$('photo-select').onchange=()=>{if(selected)loadPanorama(selected,Number($('photo-select').value));};$('show-panorama').onclick=()=>{if(selected)loadPanorama(selected,Number($('photo-select').value));};$('show-scene').onclick=()=>{clearViewer();renderProject(selected);};
async function uploadPhotos(files){
 if(upload||!files.length)return;if(!token)return toast('Poczekaj na połączenie z serwerem.');
 if(files.length>100||files.some(f=>! /\.(jpe?g|png|insp)$/i.test(f.name)||!f.size||f.size>100*1024**2)||files.reduce((n,f)=>n+f.size,0)>5*1024**3)return toast('Wybierz do 100 zdjęć INSP/JPG/PNG: maks. 100 MB każde i 5 GB razem.');
 reset();visible('source-tabs',false);visible('dropzone',false);visible('upload-state',true);$('upload-progress').value=0;
 let cancelled=false,xhr=null,project=null,loaded=0;const total=files.reduce((n,f)=>n+f.size,0);upload={abort(){cancelled=true;xhr?.abort();}};setStart();
 try{
  project=await api('/api/photos',{name:files.length===1?files[0].name:`Panoramy · ${files.length} zdjęć`,count:files.length});
  for(let i=0;i<files.length;i++){
   if(cancelled)throw new Error('Dodawanie zdjęć anulowane.');const file=files[i];$('upload-name').textContent=file.name;$('upload-label').textContent=`Zdjęcie ${i+1} / ${files.length} · sprawdzanie panoramy`;
   await new Promise((resolve,reject)=>{xhr=new XMLHttpRequest();xhr.open('POST',`/api/projects/${project.id}/photo?name=${encodeURIComponent(file.name)}`);xhr.setRequestHeader('X-Studio-Token',token);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{$('upload-progress').value=Math.round((loaded+e.loaded)/total*100);};xhr.onload=()=>{try{const data=JSON.parse(xhr.responseText);if(xhr.status>=400)reject(new Error(data.error));else resolve(data);}catch{reject(new Error('Nieprawidłowa odpowiedź serwera.'));}};xhr.onerror=()=>reject(new Error('Utracono połączenie.'));xhr.onabort=()=>reject(new Error('Dodawanie zdjęć anulowane.'));xhr.send(file);});loaded+=file.size;
  }
  if(cancelled)throw new Error('Dodawanie zdjęć anulowane.');project=await api(`/api/projects/${project.id}/finishphotos`,{});upload=null;renderProject(project,true);toast(project.state==='panorama'?'Panorama gotowa. Przeciągnij obraz, aby się rozejrzeć.':'Zdjęcia dodane. Możesz obejrzeć panoramy lub uruchomić rekonstrukcję 3D.');
 }catch(e){if(project)await api(`/api/projects/${project.id}/abortphotos`,{}).catch(()=>{});upload=null;reset();toast(e.message);}finally{upload=null;setStart();poll();}
}

function renderCleanup(project){
 const ready=project.state==='ready'&&Boolean(project.output);visible('cleanup-panel',ready);if(!ready)return;
 const c=project.cleanup,working=['processing','cancelling'].includes(c?.status),meshBusy=['processing','cancelling'].includes(project.meshExport?.status);
 $('cleanup-start').disabled=Boolean(health.busy)||working;$('cleanup-strength').disabled=working;$('reprocess').disabled=working||meshBusy;
 visible('cleanup-start',!working);visible('cleanup-working',working);$('cleanup-cancel').disabled=c?.status==='cancelling';
 $('cleanup-phase').textContent=c?.phase||'';
 $('cleanup-summary').textContent=c?.error|| (c?.status==='ready'?`Usunięto ${c.removed.toLocaleString('pl-PL')} z ${c.before.toLocaleString('pl-PL')} splatów (${(100*c.removed/c.before).toFixed(1)}%). Oceń także zachowanie drobnych detali.`:'');
 visible('cleanup-compare',Boolean(project.cleanedOutput));
 for(const variant of ['original','cleaned']){const b=$('variant-'+variant);const selectedVariant=project.output.web===project[variant+'Output']?.web;b.classList.toggle('selected',selectedVariant);b.setAttribute('aria-pressed',String(selectedVariant));b.disabled=working||meshBusy;}
 if(!panorama&&viewerKey.startsWith(project.id+':'))$('preview-badge').textContent=project.output.web===project.cleanedOutput?.web?'3D · PO CZYSZCZENIU':'3D · ORYGINAŁ';
}
$('cleanup-start').onclick=async()=>{if(!selected)return;$('cleanup-start').disabled=true;try{const p=await api(`/api/projects/${selected.id}/cleanup`,{strength:$('cleanup-strength').value});health.busy=p.id;renderProject(p);}catch(e){toast(e.message);await poll();}};
$('cleanup-cancel').onclick=async()=>{if(!selected)return;try{await api(`/api/projects/${selected.id}/cancelcleanup`,{});await poll();}catch(e){toast(e.message);}};
for(const variant of ['original','cleaned'])$('variant-'+variant).onclick=async()=>{if(!selected)return;try{const p=await api(`/api/projects/${selected.id}/variant`,{variant});clearViewer();renderProject(p);}catch(e){toast(e.message);}};

function renderBlender(project){
 const ready=project.state==='ready'&&Boolean(project.output);visible('blender-panel',ready);if(!ready)return;
 const m=project.meshExport,working=['processing','cancelling'].includes(m?.status),output=project.meshOutput;
 $('mesh-start').disabled=Boolean(health.busy)||working;visible('mesh-working',working);visible('mesh-start',!working);$('mesh-cancel').disabled=m?.status==='cancelling';
 $('mesh-phase').textContent=m?.phase||'';
 const matches=output?.sourceWeb===project.output.web;visible('download-glb',Boolean(matches));if(matches)$('download-glb').href=`/api/projects/${project.id}/glb`;
 $('mesh-summary').textContent=m?.error||(matches?`${output.faces.toLocaleString('pl-PL')} trójkątów · kolory wierzchołków · ${bytes(output.bytes)}`:output?'Zmieniono wariant sceny. Przygotuj eksport aktualnego modelu.':'');
}
$('mesh-start').onclick=async()=>{if(!selected)return;$('mesh-start').disabled=true;try{const p=await api(`/api/projects/${selected.id}/mesh`,{});health.busy=p.id;renderProject(p);}catch(e){toast(e.message);await poll();}};
$('mesh-cancel').onclick=async()=>{if(!selected)return;try{await api(`/api/projects/${selected.id}/cancelmesh`,{});await poll();}catch(e){toast(e.message);}};
